version: '3'
services:
  genomicworkbench:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin_access
      MINIO_SECRET_KEY: minioadmin_access

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_pheno
    volumes:
      - ./db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    restart: always
    ports:
      - '9000:9000'
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data   
    volumes:
      - ./minio-data:/data
